name: tgswitch

author: Stephen Attard

description: Setup tgswitch to install a specific version of terragrunt

runs:
  using: composite
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::This action is only supported on Linux Runners"
        exit 1
    - name: Install tgswitch
      shell: bash
      run: |
        echo "Downloading install script .."
        curl -sLo install.sh curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh
        echo "Configuring install script to be executable .."
        chmod 755 install.sh
        echo "Creating $HOME/.bin for tgswitch binary .."
        mkdir -p $HOME/.bin
        echo "Installing tgswitch version .."
        ./install.sh -b $HOME/.bin
        echo "Running tgswitch from $HOME/.bin .."
        $HOME/.bin/tgswitch --version
        export PATH=$PATH:$HOME/.bin
        echo "Running tgswitch assuming PATH is set .."
        tgswitch --version
        echo "Exporting PATH to GITHUB_PATH .."
        echo $HOME/.bin >> $GITHUB_PATH
        echo "Unlinking default version of terragrunt .."
        unlink /usr/local/bin/terragrunt
        echo "Done!"

branding:
  color: blue
  icon: box